<?php
/**
 * ============================================
 * FuelOps - Crear BD de TEST - Firebird
 * ============================================
 * Ejecutar: php scripts/create_test_db.php
 * 
 * Crea 15 tablas con 1000+ registros cada una
 * para testing de rendimiento y consultas.
 */

echo "============================================\n";
echo "  FuelOps - CREANDO BASE DE DATOS DE TEST\n";
echo "============================================\n\n";

// Configuración
$dbPath = 'C:\Firebird\BO5_TEST.FDB';
$user = 'SYSDBA';
$password = 'masterkey';

// Crear directorio si no existe
$dbDir = dirname($dbPath);
if (!is_dir($dbDir)) {
    mkdir($dbDir, 0777, true);
    echo "Directorio creado: {$dbDir}\n";
}

// Eliminar BD anterior si existe (fresh start)
if (file_exists($dbPath)) {
    echo "Eliminando BD anterior...\n";
    @unlink($dbPath);
    // Also remove lock files
    @unlink($dbPath . '.lock');
    @unlink($dbPath . '.nb');
    echo "  ✓ BD eliminada\n";
}

// Create database using isql if it doesn't exist
if (!file_exists($dbPath)) {
    echo "Creando BD con isql...\n";
    $isqlPath = '"C:\Program Files\Firebird\Firebird_5_0\isql.exe"';
    $createSql = "CREATE DATABASE 'localhost:{$dbPath}' user '{$user}' password '{$password}';";
    $descriptors = [
        0 => ['pipe', 'r'],
        1 => ['pipe', 'w'],
        2 => ['pipe', 'w'],
    ];
    $process = proc_open("{$isqlPath} -user {$user} -password {$password}", $descriptors, $pipes);
    if (is_resource($process)) {
        fwrite($pipes[0], $createSql . "\nQUIT;\n");
        fclose($pipes[0]);
        $stdout = stream_get_contents($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        proc_close($process);
    }
    if (!file_exists($dbPath)) {
        throw new RuntimeException("No se pudo crear la BD con isql.\nstdout: {$stdout}\nstderr: {$stderr}");
    }
    echo "  ✓ BD creada con isql\n";
}

try {
    // Crear BD fresca
    $dsn = "firebird:dbname=localhost:{$dbPath};charset=UTF8";
    $db = new PDO($dsn, $user, $password);
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    echo "✅ Conexión exitosa - Creando BD fresca\n\n";
    
    // ============================================
    // CREAR TABLAS
    // ============================================
    echo "Creando tablas...\n";
    
    // 1. CLIENTES
    $db->exec("CREATE TABLE CLIENTES (
        IDCLIENTE INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NOMBRE VARCHAR(150) NOT NULL,
        ACTIVO SMALLINT DEFAULT 1,
        EMAIL VARCHAR(150),
        NIF VARCHAR(20),
        PAIS VARCHAR(5) DEFAULT 'ES',
        PROVINCIA VARCHAR(50),
        CIUDAD VARCHAR(100),
        DIRECCION VARCHAR(200),
        CODIGO_POSTAL VARCHAR(10),
        TELEFONO VARCHAR(20),
        MOVIL VARCHAR(20),
        IDVENDEDOR INTEGER,
        IDSTATUS INTEGER DEFAULT 1,
        IDTIPOPAGO INTEGER DEFAULT 1,
        FACTURABLE SMALLINT DEFAULT 1,
        CODIGOCLIENTE VARCHAR(20),
        LIMITE_CREDITO DECIMAL(12,2) DEFAULT 0,
        SALDO DECIMAL(12,2) DEFAULT 0,
        FECHA_ALTA DATE DEFAULT CURRENT_DATE,
        FECHA_NACIMIENTO DATE,
        OBSERVACIONES VARCHAR(500)
    )");
    echo "  ✓ CLIENTES\n";
    
    // 2. FACTURAS
    $db->exec("CREATE TABLE FACTURAS (
        IDFACTURA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        IDCLIENTE INTEGER NOT NULL,
        FECHA DATE DEFAULT CURRENT_DATE,
        FECHA_VENCIMIENTO DATE,
        IMPORTE DECIMAL(12,2) DEFAULT 0,
        IMPORTE_IMPUESTOS DECIMAL(12,2) DEFAULT 0,
        IMPORTE_TOTAL DECIMAL(12,2) DEFAULT 0,
        ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
        SERIESFACTURA VARCHAR(10) DEFAULT 'A',
        NUMEROFACTURA VARCHAR(20),
        IDUSUARIO INTEGER,
        FORMA_PAGO VARCHAR(30),
        OBSERVACIONES VARCHAR(500),
        FECHA_PAGO DATE,
        IMPORTE_PAGADO DECIMAL(12,2) DEFAULT 0
    )");
    echo "  ✓ FACTURAS\n";
    
    // 3. LINEAS_FACTURA
    $db->exec("CREATE TABLE LINEAS_FACTURA (
        IDLINEA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        IDFACTURA INTEGER NOT NULL,
        IDPRODUCTO INTEGER NOT NULL,
        CANTIDAD DECIMAL(10,3) DEFAULT 0,
        PRECIO_UNITARIO DECIMAL(10,4) DEFAULT 0,
        DESCUENTO DECIMAL(5,2) DEFAULT 0,
        IMPORTE DECIMAL(12,2) DEFAULT 0,
        IMPORTE_IMPUESTO DECIMAL(12,2) DEFAULT 0
    )");
    echo "  ✓ LINEAS_FACTURA\n";
    
    // 4. PRODUCTOS
    $db->exec("CREATE TABLE PRODUCTOS (
        IDPRODUCTO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NOMBRE VARCHAR(150) NOT NULL,
        CODIGO VARCHAR(30),
        CODBARRAS VARCHAR(50),
        PRECIO_COMPRA DECIMAL(10,4) DEFAULT 0,
        PRECIO_VENTA DECIMAL(10,4) DEFAULT 0,
        UNIDAD VARCHAR(20) DEFAULT 'L',
        STOCK_ACTUAL DECIMAL(12,3) DEFAULT 0,
        STOCK_MINIMO DECIMAL(12,3) DEFAULT 0,
        STOCK_MAXIMO DECIMAL(12,3) DEFAULT 999999,
        IDPROVEEDOR INTEGER,
        IDCATEGORIA INTEGER,
        ACTIVO SMALLINT DEFAULT 1,
        CONIVA SMALLINT DEFAULT 1,
        DESCRIPCION VARCHAR(500),
        FECHA_ALTA DATE DEFAULT CURRENT_DATE
    )");
    echo "  ✓ PRODUCTOS\n";
    
    // 5. PROVEEDORES
    $db->exec("CREATE TABLE PROVEEDORES (
        IDPROVEEDOR INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NOMBRE VARCHAR(150) NOT NULL,
        NIF VARCHAR(20),
        EMAIL VARCHAR(150),
        TELEFONO VARCHAR(20),
        DIRECCION VARCHAR(200),
        CIUDAD VARCHAR(100),
        CODIGO_POSTAL VARCHAR(10),
        PROVINCIA VARCHAR(50),
        PAIS VARCHAR(5) DEFAULT 'ES',
        CONTACTO VARCHAR(100),
        ACTIVO SMALLINT DEFAULT 1,
        FORMA_PAGO VARCHAR(30),
        DIAS_PLAZO INTEGER DEFAULT 30,
        FECHA_ALTA DATE DEFAULT CURRENT_DATE,
        OBSERVACIONES VARCHAR(500)
    )");
    echo "  ✓ PROVEEDORES\n";
    
    // 6. COMPRAS
    $db->exec("CREATE TABLE COMPRAS (
        IDCOMPRA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        IDPROVEEDOR INTEGER NOT NULL,
        FECHA DATE DEFAULT CURRENT_DATE,
        FECHA_RECEPCION DATE,
        IMPORTE DECIMAL(12,2) DEFAULT 0,
        IMPORTE_IMPUESTOS DECIMAL(12,2) DEFAULT 0,
        IMPORTE_TOTAL DECIMAL(12,2) DEFAULT 0,
        ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
        NUMERO_PEDIDO VARCHAR(30),
        FORMA_PAGO VARCHAR(30),
        IDUSUARIO INTEGER,
        FECHA_PAGO DATE,
        IMPORTE_PAGADO DECIMAL(12,2) DEFAULT 0,
        OBSERVACIONES VARCHAR(500)
    )");
    echo "  ✓ COMPRAS\n";
    
    // 7. LINEAS_COMPRA
    $db->exec("CREATE TABLE LINEAS_COMPRA (
        IDLINEA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        IDCOMPRA INTEGER NOT NULL,
        IDPRODUCTO INTEGER NOT NULL,
        CANTIDAD DECIMAL(10,3) DEFAULT 0,
        PRECIO_UNITARIO DECIMAL(10,4) DEFAULT 0,
        DESCUENTO DECIMAL(5,2) DEFAULT 0,
        IMPORTE DECIMAL(12,2) DEFAULT 0,
        CANTIDAD_RECIBIDA DECIMAL(10,3) DEFAULT 0
    )");
    echo "  ✓ LINEAS_COMPRA\n";
    
    // 8. PERSONAS
    $db->exec("CREATE TABLE PERSONAS (
        IDPERSONA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NOMBRE VARCHAR(150) NOT NULL,
        APELLIDOS VARCHAR(150),
        NIF VARCHAR(20),
        TELEFONO VARCHAR(20),
        MOVIL VARCHAR(20),
        EMAIL VARCHAR(150),
        CARGO VARCHAR(80),
        DEPARTAMENTO VARCHAR(80),
        IDCLIENTE INTEGER,
        IDPROVEEDOR INTEGER,
        ACTIVO SMALLINT DEFAULT 1,
        FECHA_ALTA DATE DEFAULT CURRENT_DATE,
        FECHA_NACIMIENTO DATE,
        OBSERVACIONES VARCHAR(500)
    )");
    echo "  ✓ PERSONAS\n";
    
    // 9. ALMACENES
    $db->exec("CREATE TABLE ALMACENES (
        IDALMACEN INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NOMBRE VARCHAR(100) NOT NULL,
        DIRECCION VARCHAR(200),
        CIUDAD VARCHAR(100),
        CODIGO_POSTAL VARCHAR(10),
        PROVINCIA VARCHAR(50),
        TELEFONO VARCHAR(20),
        RESPONSABLE VARCHAR(100),
        ACTIVO SMALLINT DEFAULT 1,
        CAPACIDAD_MAX DECIMAL(12,2) DEFAULT 0,
        OBSERVACIONES VARCHAR(500)
    )");
    echo "  ✓ ALMACENES\n";
    
    // 10. STOCK
    $db->exec("CREATE TABLE STOCK (
        IDSTOCK INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        IDALMACEN INTEGER NOT NULL,
        IDPRODUCTO INTEGER NOT NULL,
        CANTIDAD DECIMAL(12,3) DEFAULT 0,
        UBICACION VARCHAR(50),
        FECHA_ULTIMO_MOV DATE,
        LOTE VARCHAR(30),
        FECHA_CADUCIDAD DATE,
        OBSERVACIONES VARCHAR(200)
    )");
    echo "  ✓ STOCK\n";
    
    // 11. MOVIMIENTOS
    $db->exec("CREATE TABLE MOVIMIENTOS (
        IDMOVIMIENTO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TIPO VARCHAR(20) NOT NULL,
        IDALMACEN_ORIGEN INTEGER,
        IDALMACEN_DESTINO INTEGER,
        IDPRODUCTO INTEGER NOT NULL,
        CANTIDAD DECIMAL(12,3) DEFAULT 0,
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        IDUSUARIO INTEGER,
        DOCUMENTO_REF VARCHAR(50),
        ESTADO VARCHAR(20) DEFAULT 'COMPLETADO',
        OBSERVACIONES VARCHAR(500)
    )");
    echo "  ✓ MOVIMIENTOS\n";
    
    // 12. BASES
    $db->exec("CREATE TABLE BASES (
        IDBASE INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NOMBRE VARCHAR(100) NOT NULL,
        DIRECCION VARCHAR(200),
        CIUDAD VARCHAR(100),
        CODIGO_POSTAL VARCHAR(10),
        PROVINCIA VARCHAR(50),
        TELEFONO VARCHAR(20),
        RESPONSABLE VARCHAR(100),
        ACTIVA SMALLINT DEFAULT 1,
        CAPACIDAD_GL DECIMAL(12,2) DEFAULT 0,
        FECHA_INAUGURACION DATE,
        OBSERVACIONES VARCHAR(500)
    )");
    echo "  ✓ BASES\n";
    
    // 13. TANQUES
    $db->exec("CREATE TABLE TANQUES (
        IDTANQUE INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        IDBASE INTEGER NOT NULL,
        NUMEROTANQUE VARCHAR(20),
        CAPACIDAD DECIMAL(10,2) DEFAULT 0,
        NIVEL_ACTUAL DECIMAL(10,2) DEFAULT 0,
        PRODUCTO VARCHAR(50),
        ESTADO VARCHAR(20) DEFAULT 'ACTIVO',
        FECHA_ULTIMALEIDA DATE,
        HORA_ULTIMALEIDA TIME,
        TEMPERATURA DECIMAL(5,2),
        PRESION DECIMAL(8,2),
        ULTIMA_CARGA DATE,
        PROXIMA_REVISION DATE,
        OBSERVACIONES VARCHAR(200)
    )");
    echo "  ✓ TANQUES\n";
    
    // 14. TARIFAS
    $db->exec("CREATE TABLE TARIFAS (
        IDTARIFA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NOMBRE VARCHAR(100) NOT NULL,
        TIPO VARCHAR(30),
        PRECIO DECIMAL(10,4) DEFAULT 0,
        IMPUESTO DECIMAL(5,2) DEFAULT 21,
        ACTIVA SMALLINT DEFAULT 1,
        FECHA_INICIO DATE,
        FECHA_FIN DATE,
        DESCRIPCION VARCHAR(500),
        APLICAR_EN VARCHAR(30) DEFAULT 'VENTA'
    )");
    echo "  ✓ TARIFAS\n";
    
    // 15. PEDIDOS
    $db->exec("CREATE TABLE PEDIDOS (
        IDPEDIDO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        IDCLIENTE INTEGER NOT NULL,
        FECHA DATE DEFAULT CURRENT_DATE,
        FECHA_ENTREGA DATE,
        ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
        IMPORTE_TOTAL DECIMAL(12,2) DEFAULT 0,
        DIRECCION_ENTREGA VARCHAR(200),
        TELEFONO_CONTACTO VARCHAR(20),
        PERSONA_CONTACTO VARCHAR(100),
        IDUSUARIO INTEGER,
        FORMA_PAGO VARCHAR(30),
        PRIORIDAD VARCHAR(10) DEFAULT 'NORMAL',
        OBSERVACIONES VARCHAR(500)
    )");
    echo "  ✓ PEDIDOS\n";
    
    // 16. LINEAS_PEDIDO
    $db->exec("CREATE TABLE LINEAS_PEDIDO (
        IDLINEA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        IDPEDIDO INTEGER NOT NULL,
        IDPRODUCTO INTEGER NOT NULL,
        CANTIDAD DECIMAL(10,3) DEFAULT 0,
        PRECIO_UNITARIO DECIMAL(10,4) DEFAULT 0,
        DESCUENTO DECIMAL(5,2) DEFAULT 0,
        IMPORTE DECIMAL(12,2) DEFAULT 0,
        CANTIDAD_SERVIDA DECIMAL(10,3) DEFAULT 0
    )");
    echo "  ✓ LINEAS_PEDIDO\n";
    
    // 17. USUARIOS
    $db->exec("CREATE TABLE USUARIOS (
        IDUSUARIO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        USERNAME VARCHAR(50) NOT NULL,
        PASSWORD_HASH VARCHAR(255),
        NOMBRE VARCHAR(150),
        EMAIL VARCHAR(150),
        ROL VARCHAR(30) DEFAULT 'operador',
        ACTIVO SMALLINT DEFAULT 1,
        ULTIMO_ACCESO TIMESTAMP,
        FECHA_CREACION DATE DEFAULT CURRENT_DATE,
        TELEFONO VARCHAR(20),
        AVATAR VARCHAR(200),
        OBSERVACIONES VARCHAR(500)
    )");
    echo "  ✓ USUARIOS\n";
    
    // 18. AUDITORIA
    $db->exec("CREATE TABLE AUDITORIA (
        IDAUDITORIA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TABLA VARCHAR(50),
        ID_REGISTRO INTEGER,
        ACCION VARCHAR(20),
        CAMPO VARCHAR(50),
        VALOR_ANTERIOR VARCHAR(500),
        VALOR_NUEVO VARCHAR(500),
        IDUSUARIO INTEGER,
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        IP_ADDRESS VARCHAR(45)
    )");
    echo "  ✓ AUDITORIA\n";
    
    // 19. FACTURAS proveedor (compras facturadas)
    $db->exec("CREATE TABLE FACTURAS_PROV (
        IDFACTURAPROV INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        IDPROVEEDOR INTEGER NOT NULL,
        NUMERO_FACTURA VARCHAR(30),
        FECHA DATE DEFAULT CURRENT_DATE,
        FECHA_VENCIMIENTO DATE,
        IMPORTE DECIMAL(12,2) DEFAULT 0,
        IMPORTE_IMPUESTOS DECIMAL(12,2) DEFAULT 0,
        IMPORTE_TOTAL DECIMAL(12,2) DEFAULT 0,
        ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
        FORMA_PAGO VARCHAR(30),
        FECHA_PAGO DATE,
        IMPORTE_PAGADO DECIMAL(12,2) DEFAULT 0,
        OBSERVACIONES VARCHAR(500)
    )");
    echo "  ✓ FACTURAS_PROV\n";
    
    // 20. ALERTAS
    $db->exec("CREATE TABLE ALERTAS (
        IDALERTA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TIPO VARCHAR(30),
        TITULO VARCHAR(150),
        MENSAJE VARCHAR(500),
        PRIORIDAD VARCHAR(10) DEFAULT 'MEDIA',
        LEIDA SMALLINT DEFAULT 0,
        IDUSUARIO INTEGER,
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FECHA_LEIDA TIMESTAMP,
        TABLA_REF VARCHAR(50),
        ID_REF INTEGER
    )");
    echo "  ✓ ALERTAS\n";
    
    echo "\n✅ 20 tablas creadas\n\n";
    
    // ============================================
    // INSERTAR DATOS - 1000+ REGISTROS
    // ============================================
    echo "Insertando datos de prueba (1000+ registros)...\n\n";
    
    $startTime = microtime(true);
    
    // --- PAISES y PROVINCIAS (para referencia) ---
    $paises = ['ES', 'PT', 'FR', 'IT', 'DE', 'NL', 'BE', 'GB'];
    $provincias = ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas'];
    $ciudades = ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Alicante', 'Córdoba', 'Valladolid', 'Vigo', 'Gijón'];
    
    // --- NOMBRES PARA GENERACIÓN ALEATORIA ---
    $nombresBase = ['Carlos', 'María', 'Pedro', 'Ana', 'Jorge', 'Laura', 'Miguel', 'Isabel', 'Andrés', 'Carmen', 'Francisco', 'Lucía', 'Roberto', 'Elena', 'David', 'Paula', 'Fernando', 'Sofía', 'Antonio', 'Patricia', 'José', 'Rosa', 'Manuel', 'Teresa', 'Rafael', 'Carmen', 'Juan', 'Pilar', 'Luis', 'Mercedes'];
    $apellidos = ['García', 'López', 'Martínez', 'Sánchez', 'Rodríguez', 'Fernández', 'Hernández', 'Moreno', 'Jiménez', 'Ruiz', 'Torres', 'Díaz', 'Vázquez', 'Ramos', 'Romero', 'Navarro', 'Muñoz', 'Medina', 'Castro', 'Vidal', 'Morales', 'Ortega', 'Delgado', 'Guerrero', 'Cruz', 'Flores', 'Reyes', 'Santos', 'Molina', 'Peña'];
    $cargos = ['Gerente', 'Director Comercial', 'Jefe de Compras', 'Contable', 'Técnico', 'Almacenero', 'Logística', 'RRHH', 'IT', 'Marketing', 'Producción', 'Calidad', 'Ventas', 'Administrativo', 'Asistente'];
    $productosCombustible = ['Gasolina 95', 'Gasolina 98', 'Diesel', 'Diesel Premium', 'GLP', 'Gasóleo Calefacción', 'Queroseno', 'Fuel Oil', 'Biodiesel', 'Gasolina Blend', 'Diesel Biodiesel', 'Gasolina Aditivada'];
    $formasPago = ['Efectivo', 'Tarjeta', 'Transferencia', 'Cheque', 'Domiciliación', 'Crédito'];
    $estadosFactura = ['PENDIENTE', 'PAGADA', 'ANULADA', 'PARCIAL', 'VENCIDA'];
    $estadosPedido = ['PENDIENTE', 'CONFIRMADO', 'EN_PREPARACION', 'ENVIADO', 'ENTREGADO', 'CANCELADO'];
    $estadosCompra = ['PENDIENTE', 'CONFIRMADO', 'EN_TRANSITO', 'RECIBIDO', 'CANCELADO'];
    
    // ============================================
    // CLIENTES - 1200 registros
    // ============================================
    echo "Insertando CLIENTES...";
    $stmt = $db->prepare("INSERT INTO CLIENTES (NOMBRE, ACTIVO, EMAIL, NIF, PAIS, PROVINCIA, CIUDAD, DIRECCION, CODIGO_POSTAL, TELEFONO, MOVIL, IDVENDEDOR, IDSTATUS, IDTIPOPAGO, FACTURABLE, CODIGOCLIENTE, LIMITE_CREDITO, SALDO, FECHA_ALTA, FECHA_NACIMIENTO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $batchSize = 100;
    $totalClientes = 1200;
    for ($i = 0; $i < $totalClientes; $i++) {
        $nombre = $nombresBase[array_rand($nombresBase)] . ' ' . $apellidos[array_rand($apellidos)] . ' ' . $apellidos[array_rand($apellidos)];
        $activo = (rand(1, 100) > 15) ? 1 : 0;
        $email = strtolower(str_replace(' ', '.', $nombre)) . rand(1, 999) . '@email.com';
        $nif = strtoupper(substr($nombresBase[array_rand($nombresBase)], 0, 1)) . rand(10000000, 99999999) . strtoupper(substr('TRWAGMYFPDXBNJZSQVHLCKE', rand(0, 22), 1));
        $pais = $paises[array_rand($paises)];
        $provincia = $provincias[array_rand($provincias)];
        $ciudad = $ciudades[array_rand($ciudades)];
        $direccion = 'Calle ' . $nombresBase[array_rand($nombresBase)] . ' ' . rand(1, 200);
        $cp = str_pad(rand(10000, 52999), 5, '0', STR_PAD_LEFT);
        $telefono = '9' . rand(10000000, 99999999);
        $movil = '6' . rand(10000000, 99999999);
        $vendedor = rand(1, 50);
        $status = (rand(1, 100) > 20) ? 1 : 2;
        $tipoPago = rand(1, 5);
        $facturable = (rand(1, 100) > 10) ? 1 : 0;
        $codigo = 'CLI' . str_pad($i + 1, 5, '0', STR_PAD_LEFT);
        $limiteCredito = rand(0, 50000);
        $saldo = rand(-5000, 15000);
        $fechaAlta = date('Y-m-d', strtotime("-" . rand(0, 1825) . " days"));
        $fechaNac = date('Y-m-d', strtotime("-" . rand(7000, 25000) . " days"));
        
        $stmt->execute([$nombre, $activo, $email, $nif, $pais, $provincia, $ciudad, $direccion, $cp, $telefono, $movil, $vendedor, $status, $tipoPago, $facturable, $codigo, $limiteCredito, $saldo, $fechaAlta, $fechaNac]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalClientes} registros\n";
    
    // ============================================
    // PROVEEDORES - 300 registros
    // ============================================
    echo "Insertando PROVEEDORES...";
    $stmt = $db->prepare("INSERT INTO PROVEEDORES (NOMBRE, NIF, EMAIL, TELEFONO, DIRECCION, CIUDAD, CODIGO_POSTAL, PROVINCIA, PAIS, CONTACTO, ACTIVO, FORMA_PAGO, DIAS_PLAZO, FECHA_ALTA) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $totalProveedores = 300;
    for ($i = 0; $i < $totalProveedores; $i++) {
        $nombre = 'Prov. ' . $nombresBase[array_rand($nombresBase)] . ' ' . $apellidos[array_rand($apellidos)];
        $nif = 'B' . rand(10000000, 99999999);
        $email = strtolower(str_replace(' ', '.', $nombre)) . '@proveedor.com';
        $telefono = '9' . rand(10000000, 99999999);
        $direccion = 'Avda. Industrial ' . rand(1, 200);
        $ciudad = $ciudades[array_rand($ciudades)];
        $cp = str_pad(rand(10000, 52999), 5, '0', STR_PAD_LEFT);
        $provincia = $provincias[array_rand($provincias)];
        $pais = $paises[array_rand($paises)];
        $contacto = $nombresBase[array_rand($nombresBase)] . ' ' . $apellidos[array_rand($apellidos)];
        $activo = (rand(1, 100) > 10) ? 1 : 0;
        $formaPago = $formasPago[array_rand($formasPago)];
        $diasPlazo = [15, 30, 45, 60, 90][rand(0, 4)];
        $fechaAlta = date('Y-m-d', strtotime("-" . rand(0, 1825) . " days"));
        
        $stmt->execute([$nombre, $nif, $email, $telefono, $direccion, $ciudad, $cp, $provincia, $pais, $contacto, $activo, $formaPago, $diasPlazo, $fechaAlta]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalProveedores} registros\n";
    
    // ============================================
    // PRODUCTOS - 500 registros
    // ============================================
    echo "Insertando PRODUCTOS...";
    $stmt = $db->prepare("INSERT INTO PRODUCTOS (NOMBRE, CODIGO, PRECIO_COMPRA, PRECIO_VENTA, UNIDAD, STOCK_ACTUAL, STOCK_MINIMO, IDPROVEEDOR, IDCATEGORIA, ACTIVO, DESCRIPCION) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $unidades = ['L', 'Kg', 'm3', 'ud', 'g', 'ml'];
    $totalProductos = 500;
    for ($i = 0; $i < $totalProductos; $i++) {
        $nombre = $productosCombustible[array_rand($productosCombustible)] . ' ' . $nombresBase[array_rand($nombresBase)];
        $codigo = 'PROD' . str_pad($i + 1, 5, '0', STR_PAD_LEFT);
        $precioCompra = rand(50, 300) + (rand(0, 99) / 100);
        $precioVenta = $precioCompra * (1 + rand(10, 40) / 100);
        $unidad = $unidades[array_rand($unidades)];
        $stock = rand(0, 50000);
        $stockMin = rand(100, 5000);
        $proveedor = rand(1, $totalProveedores);
        $categoria = rand(1, 20);
        $activo = (rand(1, 100) > 8) ? 1 : 0;
        $desc = 'Producto de prueba #' . ($i + 1);
        
        $stmt->execute([$nombre, $codigo, $precioCompra, round($precioVenta, 4), $unidad, $stock, $stockMin, $proveedor, $categoria, $activo, $desc]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalProductos} registros\n";
    
    // ============================================
    // PERSONAS - 800 registros
    // ============================================
    echo "Insertando PERSONAS...";
    $stmt = $db->prepare("INSERT INTO PERSONAS (NOMBRE, APELLIDOS, NIF, TELEFONO, MOVIL, EMAIL, CARGO, DEPARTAMENTO, IDCLIENTE, IDPROVEEDOR, ACTIVO, FECHA_ALTA) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $departamentos = ['Gerencia', 'Comercial', 'Compras', 'Finanzas', 'Técnico', 'Almacén', 'Logística', 'RRHH', 'IT', 'Marketing', 'Producción', 'Calidad', 'Ventas', 'Administración'];
    
    $totalPersonas = 800;
    for ($i = 0; $i < $totalPersonas; $i++) {
        $nombre = $nombresBase[array_rand($nombresBase)];
        $apellidosStr = $apellidos[array_rand($apellidos)] . ' ' . $apellidos[array_rand($apellidos)];
        $nif = strtoupper(substr($nombre, 0, 1)) . rand(10000000, 99999999) . strtoupper(substr('TRWAGMYFPDXBNJZSQVHLCKE', rand(0, 22), 1));
        $telefono = '9' . rand(10000000, 99999999);
        $movil = '6' . rand(10000000, 99999999);
        $email = strtolower($nombre) . '.' . strtolower($apellidos[array_rand($apellidos)]) . rand(1, 999) . '@empresa.com';
        $cargo = $cargos[array_rand($cargos)];
        $departamento = $departamentos[array_rand($departamentos)];
        $idCliente = (rand(1, 100) > 30) ? rand(1, $totalClientes) : null;
        $idProveedor = ($idCliente === null) ? rand(1, $totalProveedores) : null;
        $activo = (rand(1, 100) > 12) ? 1 : 0;
        $fechaAlta = date('Y-m-d', strtotime("-" . rand(0, 1825) . " days"));
        
        $stmt->execute([$nombre, $apellidosStr, $nif, $telefono, $movil, $email, $cargo, $departamento, $idCliente, $idProveedor, $activo, $fechaAlta]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalPersonas} registros\n";
    
    // ============================================
    // FACTURAS - 2000 registros
    // ============================================
    echo "Insertando FACTURAS...";
    $stmt = $db->prepare("INSERT INTO FACTURAS (IDCLIENTE, FECHA, FECHA_VENCIMIENTO, IMPORTE, IMPORTE_IMPUESTOS, IMPORTE_TOTAL, ESTADO, SERIESFACTURA, NUMEROFACTURA, IDUSUARIO, FORMA_PAGO, FECHA_PAGO, IMPORTE_PAGADO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $totalFacturas = 2000;
    for ($i = 0; $i < $totalFacturas; $i++) {
        $idCliente = rand(1, $totalClientes);
        $fecha = date('Y-m-d', strtotime("-" . rand(0, 730) . " days"));
        $fechaVenc = date('Y-m-d', strtotime($fecha . "+" . [15, 30, 45, 60, 90][rand(0, 4)] . " days"));
        $importe = rand(50, 25000) + (rand(0, 99) / 100);
        $impuestos = round($importe * 0.21, 2);
        $total = round($importe + $impuestos, 2);
        $estado = $estadosFactura[array_rand($estadosFactura)];
        $serie = ['A', 'B', 'C', 'S'][rand(0, 3)];
        $numero = $serie . str_pad($i + 1, 8, '0', STR_PAD_LEFT);
        $usuario = rand(1, 20);
        $formaPago = $formasPago[array_rand($formasPago)];
        $fechaPago = ($estado === 'PAGADA') ? date('Y-m-d', strtotime($fecha . "+" . rand(1, 30) . " days")) : null;
        $importePagado = ($estado === 'PAGADA') ? $total : (($estado === 'PARCIAL') ? round($total * (rand(30, 70) / 100), 2) : 0);
        
        $stmt->execute([$idCliente, $fecha, $fechaVenc, $importe, $impuestos, $total, $estado, $serie, $numero, $usuario, $formaPago, $fechaPago, $importePagado]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalFacturas} registros\n";
    
    // ============================================
    // LINEAS_FACTURA - 6000 registros
    // ============================================
    echo "Insertando LINEAS_FACTURA...";
    $stmt = $db->prepare("INSERT INTO LINEAS_FACTURA (IDFACTURA, IDPRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO, IMPORTE, IMPORTE_IMPUESTO) VALUES (?, ?, ?, ?, ?, ?, ?)");
    
    $totalLineasF = 6000;
    for ($i = 0; $i < $totalLineasF; $i++) {
        $idFactura = rand(1, $totalFacturas);
        $idProducto = rand(1, $totalProductos);
        $cantidad = rand(1, 500) + (rand(0, 999) / 1000);
        $precio = rand(1, 500) + (rand(0, 99) / 100);
        $descuento = [0, 0, 0, 5, 10, 15, 20][rand(0, 6)];
        $importe = round($cantidad * $precio * (1 - $descuento / 100), 2);
        $impuesto = round($importe * 0.21, 2);
        
        $stmt->execute([$idFactura, $idProducto, $cantidad, $precio, $descuento, $importe, $impuesto]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalLineasF} registros\n";
    
    // ============================================
    // COMPRAS - 1500 registros
    // ============================================
    echo "Insertando COMPRAS...";
    $stmt = $db->prepare("INSERT INTO COMPRAS (IDPROVEEDOR, FECHA, FECHA_RECEPCION, IMPORTE, IMPORTE_IMPUESTOS, IMPORTE_TOTAL, ESTADO, NUMERO_PEDIDO, FORMA_PAGO, IDUSUARIO, FECHA_PAGO, IMPORTE_PAGADO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $totalCompras = 1500;
    for ($i = 0; $i < $totalCompras; $i++) {
        $idProveedor = rand(1, $totalProveedores);
        $fecha = date('Y-m-d', strtotime("-" . rand(0, 365) . " days"));
        $fechaRecep = (rand(1, 100) > 30) ? date('Y-m-d', strtotime($fecha . "+" . rand(1, 15) . " days")) : null;
        $importe = rand(100, 30000) + (rand(0, 99) / 100);
        $impuestos = round($importe * 0.21, 2);
        $total = round($importe + $impuestos, 2);
        $estado = $estadosCompra[array_rand($estadosCompra)];
        $numPedido = 'PED' . str_pad($i + 1, 8, '0', STR_PAD_LEFT);
        $formaPago = $formasPago[array_rand($formasPago)];
        $usuario = rand(1, 20);
        $fechaPago = ($estado === 'RECIBIDO') ? date('Y-m-d', strtotime($fecha . "+" . rand(1, 45) . " days")) : null;
        $importePagado = ($estado === 'RECIBIDO') ? $total : 0;
        
        $stmt->execute([$idProveedor, $fecha, $fechaRecep, $importe, $impuestos, $total, $estado, $numPedido, $formaPago, $usuario, $fechaPago, $importePagado]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalCompras} registros\n";
    
    // ============================================
    // LINEAS_COMPRA - 4500 registros
    // ============================================
    echo "Insertando LINEAS_COMPRA...";
    $stmt = $db->prepare("INSERT INTO LINEAS_COMPRA (IDCOMPRA, IDPRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO, IMPORTE, CANTIDAD_RECIBIDA) VALUES (?, ?, ?, ?, ?, ?, ?)");
    
    $totalLineasC = 4500;
    for ($i = 0; $i < $totalLineasC; $i++) {
        $idCompra = rand(1, $totalCompras);
        $idProducto = rand(1, $totalProductos);
        $cantidad = rand(10, 2000);
        $precio = rand(1, 300) + (rand(0, 99) / 100);
        $descuento = [0, 0, 0, 3, 5, 10][rand(0, 5)];
        $importe = round($cantidad * $precio * (1 - $descuento / 100), 2);
        $cantRecibida = (rand(1, 100) > 15) ? $cantidad : rand(0, $cantidad);
        
        $stmt->execute([$idCompra, $idProducto, $cantidad, $precio, $descuento, $importe, $cantRecibida]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalLineasC} registros\n";
    
    // ============================================
    // PEDIDOS - 1800 registros
    // ============================================
    echo "Insertando PEDIDOS...";
    $stmt = $db->prepare("INSERT INTO PEDIDOS (IDCLIENTE, FECHA, FECHA_ENTREGA, ESTADO, IMPORTE_TOTAL, DIRECCION_ENTREGA, TELEFONO_CONTACTO, PERSONA_CONTACTO, IDUSUARIO, FORMA_PAGO, PRIORIDAD) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $prioridades = ['BAJA', 'NORMAL', 'ALTA', 'URGENTE'];
    $totalPedidos = 1800;
    for ($i = 0; $i < $totalPedidos; $i++) {
        $idCliente = rand(1, $totalClientes);
        $fecha = date('Y-m-d', strtotime("-" . rand(0, 365) . " days"));
        $fechaEntrega = date('Y-m-d', strtotime($fecha . "+" . rand(1, 30) . " days"));
        $estado = $estadosPedido[array_rand($estadosPedido)];
        $total = rand(100, 15000) + (rand(0, 99) / 100);
        $direccion = 'Calle ' . $nombresBase[array_rand($nombresBase)] . ' ' . rand(1, 200);
        $telefono = '6' . rand(10000000, 99999999);
        $persona = $nombresBase[array_rand($nombresBase)] . ' ' . $apellidos[array_rand($apellidos)];
        $usuario = rand(1, 20);
        $formaPago = $formasPago[array_rand($formasPago)];
        $prioridad = $prioridades[array_rand($prioridades)];
        
        $stmt->execute([$idCliente, $fecha, $fechaEntrega, $estado, $total, $direccion, $telefono, $persona, $usuario, $formaPago, $prioridad]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalPedidos} registros\n";
    
    // ============================================
    // LINEAS_PEDIDO - 5400 registros
    // ============================================
    echo "Insertando LINEAS_PEDIDO...";
    $stmt = $db->prepare("INSERT INTO LINEAS_PEDIDO (IDPEDIDO, IDPRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO, IMPORTE, CANTIDAD_SERVIDA) VALUES (?, ?, ?, ?, ?, ?, ?)");
    
    $totalLineasP = 5400;
    for ($i = 0; $i < $totalLineasP; $i++) {
        $idPedido = rand(1, $totalPedidos);
        $idProducto = rand(1, $totalProductos);
        $cantidad = rand(1, 500);
        $precio = rand(1, 400) + (rand(0, 99) / 100);
        $descuento = [0, 0, 0, 5, 10][rand(0, 4)];
        $importe = round($cantidad * $precio * (1 - $descuento / 100), 2);
        $cantServida = (rand(1, 100) > 10) ? $cantidad : rand(0, $cantidad);
        
        $stmt->execute([$idPedido, $idProducto, $cantidad, $precio, $descuento, $importe, $cantServida]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalLineasP} registros\n";
    
    // ============================================
    // ALMACENES - 100 registros
    // ============================================
    echo "Insertando ALMACENES...";
    $stmt = $db->prepare("INSERT INTO ALMACENES (NOMBRE, DIRECCION, CIUDAD, CODIGO_POSTAL, PROVINCIA, TELEFONO, RESPONSABLE, ACTIVO, CAPACIDAD_MAX) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $tiposAlmacen = ['Centro Logístico', 'Almacén Central', 'Depósito Norte', 'Depósito Sur', 'Planta de Mezclas', 'Almacén Temporal', 'Centro de Distribución', 'Hub Logístico'];
    $totalAlmacenes = 100;
    for ($i = 0; $i < $totalAlmacenes; $i++) {
        $nombre = $tiposAlmacen[array_rand($tiposAlmacen)] . ' #' . ($i + 1);
        $direccion = 'Polígono Industrial ' . $nombresBase[array_rand($nombresBase)] . ' ' . rand(1, 100);
        $ciudad = $ciudades[array_rand($ciudades)];
        $cp = str_pad(rand(10000, 52999), 5, '0', STR_PAD_LEFT);
        $provincia = $provincias[array_rand($provincias)];
        $telefono = '9' . rand(10000000, 99999999);
        $responsable = $nombresBase[array_rand($nombresBase)] . ' ' . $apellidos[array_rand($apellidos)];
        $activo = (rand(1, 100) > 5) ? 1 : 0;
        $capacidad = rand(5000, 100000);
        
        $stmt->execute([$nombre, $direccion, $ciudad, $cp, $provincia, $telefono, $responsable, $activo, $capacidad]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalAlmacenes} registros\n";
    
    // ============================================
    // STOCK - 3000 registros
    // ============================================
    echo "Insertando STOCK...";
    $stmt = $db->prepare("INSERT INTO STOCK (IDALMACEN, IDPRODUCTO, CANTIDAD, UBICACION, FECHA_ULTIMO_MOV, LOTE, FECHA_CADUCIDAD) VALUES (?, ?, ?, ?, ?, ?, ?)");
    
    $totalStock = 3000;
    for ($i = 0; $i < $totalStock; $i++) {
        $idAlmacen = rand(1, $totalAlmacenes);
        $idProducto = rand(1, $totalProductos);
        $cantidad = rand(0, 50000);
        $ubicacion = 'Zona ' . chr(65 + rand(0, 5)) . '-P' . rand(1, 10) . '-E' . rand(1, 20);
        $fechaMov = date('Y-m-d', strtotime("-" . rand(0, 90) . " days"));
        $lote = 'LOT' . date('ym') . str_pad(rand(1, 9999), 4, '0', STR_PAD_LEFT);
        $fechaCad = (rand(1, 100) > 60) ? date('Y-m-d', strtotime("+" . rand(30, 730) . " days")) : null;
        
        $stmt->execute([$idAlmacen, $idProducto, $cantidad, $ubicacion, $fechaMov, $lote, $fechaCad]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalStock} registros\n";
    
    // ============================================
    // MOVIMIENTOS - 4000 registros
    // ============================================
    echo "Insertando MOVIMIENTOS...";
    $stmt = $db->prepare("INSERT INTO MOVIMIENTOS (TIPO, IDALMACEN_ORIGEN, IDALMACEN_DESTINO, IDPRODUCTO, CANTIDAD, FECHA, IDUSUARIO, DOCUMENTO_REF, ESTADO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $tiposMov = ['ENTRADA', 'SALIDA', 'TRASPASO', 'AJUSTE', 'DEVOLUCION'];
    $estadosMov = ['COMPLETADO', 'PENDIENTE', 'CANCELADO'];
    $totalMovimientos = 4000;
    for ($i = 0; $i < $totalMovimientos; $i++) {
        $tipo = $tiposMov[array_rand($tiposMov)];
        $almacenOrigen = ($tipo === 'ENTRADA') ? null : rand(1, $totalAlmacenes);
        $almacenDestino = ($tipo === 'SALIDA') ? null : rand(1, $totalAlmacenes);
        $idProducto = rand(1, $totalProductos);
        $cantidad = rand(1, 5000);
        $fecha = date('Y-m-d H:i:s', strtotime("-" . rand(0, 365) . " days -" . rand(0, 23) . " hours"));
        $usuario = rand(1, 20);
        $docRef = strtoupper($tipo) . '-' . str_pad($i + 1, 8, '0', STR_PAD_LEFT);
        $estado = $estadosMov[array_rand($estadosMov)];
        
        $stmt->execute([$tipo, $almacenOrigen, $almacenDestino, $idProducto, $cantidad, $fecha, $usuario, $docRef, $estado]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalMovimientos} registros\n";
    
    // ============================================
    // BASES - 150 registros
    // ============================================
    echo "Insertando BASES...";
    $stmt = $db->prepare("INSERT INTO BASES (NOMBRE, DIRECCION, CIUDAD, CODIGO_POSTAL, PROVINCIA, TELEFONO, RESPONSABLE, ACTIVA, CAPACIDAD_GL) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $totalBases = 150;
    for ($i = 0; $i < $totalBases; $i++) {
        $nombre = 'Base ' . $nombresBase[array_rand($nombresBase)] . ' ' . ($i + 1);
        $direccion = 'Ctra. ' . $nombresBase[array_rand($nombresBase)] . ' ' . rand(1, 100);
        $ciudad = $ciudades[array_rand($ciudades)];
        $cp = str_pad(rand(10000, 52999), 5, '0', STR_PAD_LEFT);
        $provincia = $provincias[array_rand($provincias)];
        $telefono = '9' . rand(10000000, 99999999);
        $responsable = $nombresBase[array_rand($nombresBase)] . ' ' . $apellidos[array_rand($apellidos)];
        $activa = (rand(1, 100) > 8) ? 1 : 0;
        $capacidad = rand(10000, 200000);
        
        $stmt->execute([$nombre, $direccion, $ciudad, $cp, $provincia, $telefono, $responsable, $activa, $capacidad]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalBases} registros\n";
    
    // ============================================
    // TANQUES - 600 registros
    // ============================================
    echo "Insertando TANQUES...";
    $stmt = $db->prepare("INSERT INTO TANQUES (IDBASE, NUMEROTANQUE, CAPACIDAD, NIVEL_ACTUAL, PRODUCTO, ESTADO, FECHA_ULTIMALEIDA, HORA_ULTIMALEIDA, TEMPERATURA, PRESION, ULTIMA_CARGA, PROXIMA_REVISION) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $estadosTanque = ['ACTIVO', 'MANTENIMIENTO', 'INACTIVO', 'EN_CARGA', 'VACIO'];
    $totalTanques = 600;
    for ($i = 0; $i < $totalTanques; $i++) {
        $idBase = rand(1, $totalBases);
        $numTanque = 'T-' . str_pad(rand(1, 999), 3, '0', STR_PAD_LEFT);
        $capacidad = [20000, 30000, 40000, 50000, 60000, 80000][rand(0, 5)];
        $nivel = rand(0, intval($capacidad * 0.95));
        $producto = $productosCombustible[array_rand($productosCombustible)];
        $estado = $estadosTanque[array_rand($estadosTanque)];
        $fechaLectura = date('Y-m-d', strtotime("-" . rand(0, 7) . " days"));
        $horaLectura = str_pad(rand(0, 23), 2, '0', STR_PAD_LEFT) . ':' . str_pad(rand(0, 59), 2, '0', STR_PAD_LEFT) . ':00';
        $temp = rand(5, 45) + (rand(0, 9) / 10);
        $presion = rand(1, 5) + (rand(0, 9) / 10);
        $ultimaCarga = date('Y-m-d', strtotime("-" . rand(0, 30) . " days"));
        $proxRevision = date('Y-m-d', strtotime("+" . rand(15, 180) . " days"));
        
        $stmt->execute([$idBase, $numTanque, $capacidad, $nivel, $producto, $estado, $fechaLectura, $horaLectura, $temp, $presion, $ultimaCarga, $proxRevision]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalTanques} registros\n";
    
    // ============================================
    // TARIFAS - 200 registros
    // ============================================
    echo "Insertando TARIFAS...";
    $stmt = $db->prepare("INSERT INTO TARIFAS (NOMBRE, TIPO, PRECIO, IMPUESTO, ACTIVA, FECHA_INICIO, FECHA_FIN, DESCRIPCION, APLICAR_EN) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $tiposTarifa = ['VENTA', 'COMPRA', 'ESPECIAL', 'PROMOCIONAL', 'MAYORISTA'];
    $totalTarifas = 200;
    for ($i = 0; $i < $totalTarifas; $i++) {
        $nombre = 'Tarifa ' . $nombresBase[array_rand($nombresBase)] . ' #' . ($i + 1);
        $tipo = $tiposTarifa[array_rand($tiposTarifa)];
        $precio = rand(50, 500) + (rand(0, 99) / 100);
        $impuesto = [0, 4, 10, 21][rand(0, 3)];
        $activa = (rand(1, 100) > 15) ? 1 : 0;
        $fechaInicio = date('Y-m-d', strtotime("-" . rand(0, 365) . " days"));
        $fechaFin = date('Y-m-d', strtotime($fechaInicio . "+" . rand(30, 365) . " days"));
        $desc = 'Tarifa de ' . strtolower($tipo) . ' para testing';
        $aplicarEn = (rand(1, 100) > 50) ? 'VENTA' : 'COMPRA';
        
        $stmt->execute([$nombre, $tipo, $precio, $impuesto, $activa, $fechaInicio, $fechaFin, $desc, $aplicarEn]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalTarifas} registros\n";
    
    // ============================================
    // USUARIOS - 50 registros
    // ============================================
    echo "Insertando USUARIOS...";
    $stmt = $db->prepare("INSERT INTO USUARIOS (USERNAME, PASSWORD_HASH, NOMBRE, EMAIL, ROL, ACTIVO, ULTIMO_ACCESO, FECHA_CREACION, TELEFONO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $roles = ['admin', 'analista', 'operador', 'readonly', 'tecnico', 'compras', 'ventas'];
    $totalUsuarios = 50;
    for ($i = 0; $i < $totalUsuarios; $i++) {
        $username = strtolower($nombresBase[array_rand($nombresBase)] . '.' . $apellidos[array_rand($apellidos)] . $i);
        $passwordHash = password_hash('password' . $i, PASSWORD_DEFAULT);
        $nombre = $nombresBase[array_rand($nombresBase)] . ' ' . $apellidos[array_rand($apellidos)];
        $email = $username . '@fuelops.com';
        $rol = $roles[array_rand($roles)];
        $activo = (rand(1, 100) > 10) ? 1 : 0;
        $ultimoAcceso = date('Y-m-d H:i:s', strtotime("-" . rand(0, 90) . " days"));
        $fechaCreacion = date('Y-m-d', strtotime("-" . rand(0, 730) . " days"));
        $telefono = '6' . rand(10000000, 99999999);
        
        $stmt->execute([$username, $passwordHash, $nombre, $email, $rol, $activo, $ultimoAcceso, $fechaCreacion, $telefono]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalUsuarios} registros\n";
    
    // ============================================
    // AUDITORIA - 3000 registros
    // ============================================
    echo "Insertando AUDITORIA...";
    $stmt = $db->prepare("INSERT INTO AUDITORIA (TABLA, ID_REGISTRO, ACCION, CAMPO, VALOR_ANTERIOR, VALOR_NUEVO, IDUSUARIO, FECHA, IP_ADDRESS) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $tablasAud = ['CLIENTES', 'FACTURAS', 'PRODUCTOS', 'COMPRAS', 'PEDIDOS', 'USUARIOS'];
    $acciones = ['INSERT', 'UPDATE', 'DELETE'];
    $campos = ['NOMBRE', 'EMAIL', 'ESTADO', 'IMPORTE', 'PRECIO', 'STOCK', 'ACTIVO'];
    $totalAuditoria = 3000;
    for ($i = 0; $i < $totalAuditoria; $i++) {
        $tabla = $tablasAud[array_rand($tablasAud)];
        $idRegistro = rand(1, 1000);
        $accion = $acciones[array_rand($acciones)];
        $campo = $campos[array_rand($campos)];
        $valorAnt = 'valor_anterior_' . rand(1, 999);
        $valorNue = 'valor_nuevo_' . rand(1, 999);
        $usuario = rand(1, $totalUsuarios);
        $fecha = date('Y-m-d H:i:s', strtotime("-" . rand(0, 365) . " days -" . rand(0, 23) . " hours"));
        $ip = rand(192, 192) . '.' . rand(168, 168) . '.' . rand(1, 10) . '.' . rand(1, 254);
        
        $stmt->execute([$tabla, $idRegistro, $accion, $campo, $valorAnt, $valorNue, $usuario, $fecha, $ip]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalAuditoria} registros\n";
    
    // ============================================
    // FACTURAS_PROV - 1000 registros
    // ============================================
    echo "Insertando FACTURAS_PROV...";
    $stmt = $db->prepare("INSERT INTO FACTURAS_PROV (IDPROVEEDOR, NUMERO_FACTURA, FECHA, FECHA_VENCIMIENTO, IMPORTE, IMPORTE_IMPUESTOS, IMPORTE_TOTAL, ESTADO, FORMA_PAGO, FECHA_PAGO, IMPORTE_PAGADO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $totalFacturasProv = 1000;
    for ($i = 0; $i < $totalFacturasProv; $i++) {
        $idProveedor = rand(1, $totalProveedores);
        $numFactura = 'FP-' . str_pad($i + 1, 8, '0', STR_PAD_LEFT);
        $fecha = date('Y-m-d', strtotime("-" . rand(0, 365) . " days"));
        $fechaVenc = date('Y-m-d', strtotime($fecha . "+" . [15, 30, 45, 60][rand(0, 3)] . " days"));
        $importe = rand(200, 20000) + (rand(0, 99) / 100);
        $impuestos = round($importe * 0.21, 2);
        $total = round($importe + $impuestos, 2);
        $estado = $estadosFactura[array_rand($estadosFactura)];
        $formaPago = $formasPago[array_rand($formasPago)];
        $fechaPago = ($estado === 'PAGADA') ? date('Y-m-d', strtotime($fecha . "+" . rand(1, 30) . " days")) : null;
        $importePagado = ($estado === 'PAGADA') ? $total : 0;
        
        $stmt->execute([$idProveedor, $numFactura, $fecha, $fechaVenc, $importe, $impuestos, $total, $estado, $formaPago, $fechaPago, $importePagado]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalFacturasProv} registros\n";
    
    // ============================================
    // ALERTAS - 500 registros
    // ============================================
    echo "Insertando ALERTAS...";
    $stmt = $db->prepare("INSERT INTO ALERTAS (TIPO, TITULO, MENSAJE, PRIORIDAD, LEIDA, IDUSUARIO, FECHA, FECHA_LEIDA, TABLA_REF, ID_REF) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    
    $tiposAlerta = ['STOCK_BAJO', 'FACTURA_VENCIDA', 'PEDIDO_PENDIENTE', 'TANQUE_VACIO', 'SISTEMA', 'SEGURIDAD'];
    $prioridades = ['BAJA', 'MEDIA', 'ALTA', 'CRITICA'];
    $totalAlertas = 500;
    for ($i = 0; $i < $totalAlertas; $i++) {
        $tipo = $tiposAlerta[array_rand($tiposAlerta)];
        $titulo = 'Alerta: ' . str_replace('_', ' ', $tipo);
        $mensaje = 'Notificación de prueba #' . ($i + 1) . ' - ' . $tipo;
        $prioridad = $prioridades[array_rand($prioridades)];
        $leida = (rand(1, 100) > 40) ? 1 : 0;
        $usuario = rand(1, $totalUsuarios);
        $fecha = date('Y-m-d H:i:s', strtotime("-" . rand(0, 90) . " days"));
        $fechaLeida = $leida ? date('Y-m-d H:i:s', strtotime($fecha . "+" . rand(1, 48) . " hours")) : null;
        $tablaRef = $tablasAud[array_rand($tablasAud)];
        $idRef = rand(1, 1000);
        
        $stmt->execute([$tipo, $titulo, $mensaje, $prioridad, $leida, $usuario, $fecha, $fechaLeida, $tablaRef, $idRef]);
        
        if (($i + 1) % $batchSize === 0) echo ".";
    }
    echo " {$totalAlertas} registros\n";
    
    $elapsed = round(microtime(true) - $startTime, 2);
    echo "\n✅ Todos los datos insertados en {$elapsed}s\n\n";
    
    // ============================================
    // VERIFICAR
    // ============================================
    echo "============================================\n";
    echo "  VERIFICACIÓN FINAL\n";
    echo "============================================\n\n";
    
    $tablas = [
        'CLIENTES', 'PROVEEDORES', 'PRODUCTOS', 'PERSONAS',
        'FACTURAS', 'LINEAS_FACTURA', 'COMPRAS', 'LINEAS_COMPRA',
        'PEDIDOS', 'LINEAS_PEDIDO', 'ALMACENES', 'STOCK',
        'MOVIMIENTOS', 'BASES', 'TANQUES', 'TARIFAS',
        'USUARIOS', 'AUDITORIA', 'FACTURAS_PROV', 'ALERTAS'
    ];
    
    $grandTotal = 0;
    foreach ($tablas as $tabla) {
        $result = $db->query("SELECT COUNT(*) AS total FROM {$tabla}")->fetch(PDO::FETCH_ASSOC);
        $count = $result['TOTAL'];
        $grandTotal += $count;
        $bar = str_repeat('█', min(40, intval($count / 100)));
        echo sprintf("  %-20s %6d  %s\n", $tabla, $count, $bar);
    }
    
    echo "\n  " . str_repeat('-', 50) . "\n";
    echo sprintf("  %-20s %6d\n", 'TOTAL', $grandTotal);
    echo "\n============================================\n";
    echo "✅ BASE DE DATOS CREADA EXITOSAMENTE\n";
    echo "============================================\n\n";
    echo "Ruta: {$dbPath}\n";
    echo "Usuario: {$user}\n";
    echo "Contraseña: {$password}\n";
    echo "Tablas: " . count($tablas) . "\n";
    echo "Registros totales: {$grandTotal}\n";
    
} catch (PDOException $e) {
    echo "\n❌ ERROR: " . $e->getMessage() . "\n";
    echo "Stack trace:\n" . $e->getTraceAsString() . "\n";
    exit(1);
}
